name: Run Gradle on PRs
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  gradle:
    name: Gradle for Ghidra ${{ matrix.ghidra-version }}
    strategy:
      fail-fast: false
      matrix:
        ghidra-version: ['12.1', '12.1.2'] # TODO: '12.1.3'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: antoniovazquezblanco/setup-ghidra@v2.0.16
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra-version }}
    - name: Execute Gradle Test
      run: ${{ env.GHIDRA_INSTALL_DIR }}/support/gradle/gradlew test -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
    - name: Execute Gradle build
      run: ${{ env.GHIDRA_INSTALL_DIR }}/support/gradle/gradlew -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
    - name: Upload Zip
      uses: actions/upload-artifact@v7
      with:
        name: Extension build for Ghidra ${{ matrix.ghidra-version }}
        path: dist/*.zip
        archive: false
    # - name: Release
    #   uses: softprops/action-gh-release@v3
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: |
    #       ./dist/*.zip
